# SwiftLint Configuration for Hotaru
# https://github.com/realm/SwiftLint

# Paths to exclude from linting
excluded:
  - Pods
  - Firefly.xcodeproj
  - Firefly.xcworkspace
  - .build
  - DerivedData
  - Firefly/Preview Content

# Paths to include (optional, by default everything is included)
included:
  - Firefly

# Disable specific rules
disabled_rules:
  - trailing_whitespace # Let SwiftFormat handle this
  - trailing_comma # Preference varies
  - todo # Allow TODO comments
  - identifier_name # Too strict for existing codebase

# Opt-in rules (not enabled by default)
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Analyzer rules (require full compilation)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Configure specific rules
line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 600
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 120

type_name:
  min_length: 3
  max_length: 50
  excluded:
    - ID
    - URL
    - API
  severity: warning

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

nesting:
  type_level:
    warning: 3

# Require newlines
vertical_whitespace:
  max_empty_lines: 2

force_cast:
  severity: warning

force_try:
  severity: warning

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  double_space:
    name: "Double space"
    regex: '([a-z,A-Z] \s+)'
    message: "Double space between words"
    match_kinds:
      - comment
      - string

# Reporter type
reporter: "xcode"
